name: Build

on:
  pull_request:
    types:
      - opened
      - edited
  push:

jobs:
  build:
    name: Build
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "microsoft"
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/libs
