name: Build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK version ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "microsoft"
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != "Windows" }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture build artifacts
        if: ${{ runner.os == "Linux" && matrix.java == "17" }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs
